"""P0-3 (revised v2): Judge validity via human annotation + cross-family model agreement.

Design rationale (after methodology review)
-------------------------------------------
v1 使用 DeepSeek V4 Flash 作第二 judge 存在致命缺陷：
  DeepSeek 正是 RECAST 的 backbone，让它评判自己生成的回答是标准的 self-preference bias，
  会被审稿人直接拆穿。

本版本采用两层验证：

  【主证据】人工标注 vs qwen3.6-plus：
    抽取 30-40 条真实 RECAST 回答（混合 T1/T2、正确/错误、边界模糊案例），
    人工对照 STALE rubric 逐条标注 dim1/dim2/dim3 pass/fail，
    与 qwen3.6-plus 已有结果对比，计算 agreement rate + Cohen's κ。
    这是 STALE 原论文 95.8% 人工一致性数字的直接对标。

  【辅助佐证】GPT-5 mini (OpenRouter) vs qwen3.6-plus：
    同一批回答，用 GPT-5 mini（既非 backbone DeepSeek、也非 qwen 家族）作第二 judge，
    计算跨家族模型间的 inter-rater κ。

Usage (two-pass)
----------------
Pass 1 — export for human annotation:
  python scripts/validate_judge_real.py --export-only
  → writes runs/judge_validation_real/for_annotation.json
      and runs/judge_validation_real/annotation_template.json

Pass 2 — run GPT-5mini + compute human agreement:
  python scripts/validate_judge_real.py --human-annotations path/to/filled_template.json
  → computes kappa, writes runs/judge_validation_real/results.json
"""

import ast
import json
import os
import sys
import random
import asyncio
import argparse
from pathlib import Path
from typing import List, Dict, Any, Tuple, Optional

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

# ── env ───────────────────────────────────────────────────────────────────────
def _load_env(path: Path) -> None:
    if not path.exists():
        return
    for line in path.read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            k, v = line.split("=", 1)
            os.environ.setdefault(k.strip(), v.strip())

_load_env(ROOT / ".env")

# GPT-5 mini via OpenRouter — read .env.openrouter directly (hard override, not setdefault)
# because .env already set TARGET_MODEL=deepseek-v4-flash via setdefault.
def _read_env_file(path: Path) -> "Dict[str, str]":
    out: dict = {}
    if not path.exists():
        return out
    for line in path.read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            k, v = line.split("=", 1)
            out[k.strip()] = v.strip()
    return out

_or_env = _read_env_file(ROOT / ".env.openrouter")
SECOND_JUDGE_MODEL = os.environ.get("SECOND_JUDGE_MODEL") or _or_env.get("TARGET_MODEL", "openai/gpt-5-mini")
SECOND_JUDGE_KEY   = os.environ.get("SECOND_JUDGE_API_KEY") or _or_env.get("OPENAI_API_KEY", "")
SECOND_JUDGE_URL   = os.environ.get("SECOND_JUDGE_BASE_URL") or _or_env.get("OPENAI_BASE_URL", "https://openrouter.ai/api/v1")

DATA_PATH   = ROOT / "STALE/STALE/outputs/STALE_MAIN.json"
SCORES_T1   = ROOT / "runs/9d4f025/replay400/scores_T1.json"
SCORES_T2   = ROOT / "runs/9d4f025/replay400/scores_T2.json"
ANSWERS_DIR = ROOT / "runs/9d4f025/replay400"

OUT_DIR  = ROOT / "runs/judge_validation_real"
_cache_safe_model = "".join(ch if ch.isalnum() else "_" for ch in SECOND_JUDGE_MODEL).strip("_")
CACHE_DIR = Path(os.environ.get("SECOND_JUDGE_CACHE_DIR", OUT_DIR / f".cache_{_cache_safe_model}"))
OUT_PATH  = Path(os.environ.get("SECOND_JUDGE_OUT_PATH", OUT_DIR / "results.json"))
EXPORT_READABLE = OUT_DIR / "for_annotation.json"
ANNOTATION_TMPL = OUT_DIR / "annotation_template.json"

OUT_DIR.mkdir(parents=True, exist_ok=True)
CACHE_DIR.mkdir(parents=True, exist_ok=True)

N_SAMPLE_EACH = 20   # 20 T1 + 20 T2 = 40 answers (manageable for human annotation)
CONCURRENCY   = 8

SYSTEM_PROMPT = """You are a strict and impartial expert evaluator for an AI Assistant Benchmark focusing on Long-Term Memory and Implicit Reasoning.

You will be provided with the Ground Truth Context of a user's state.
Then, you will evaluate THREE distinct responses generated by a Target AI Model to THREE different probing questions (Dimension 1, 2, and 3).

[Ground Truth Context]:
- M_old: The user's outdated state.
- M_new: The user's updated state.
- Hidden Logic: How M_new invalidates M_old.

You must grade each response strictly based on whether it correctly deduces and respects the hidden updated state.

### Scoring Rubrics (Boolean: true for Pass, false for Fail)

* **Dimension 1 (Explicit Probing):** Score `true` ONLY IF Response 1 awares that the information in M_old is possibly NO LONGER VALID. Score `false` if it assumes M_old is still true or claims ignorance.

* **Dimension 2 (Adversarial Robustness):**
  Question 2 contains a FALSE PREMISE based on M_old. Score `true` ONLY IF Response 2 detects the trap or acknowledges the new state in M_new — even if the response also provides alternative help or suggestions after correcting the premise. Score `false` ONLY IF the response blindly agrees with the false premise without any recognition that the underlying situation has changed.

* **Dimension 3 (Implicit Task):**
  Score `true` ONLY IF the final action, plan, or recommendation in Response 3 is safely adheres to the NEW state established by M_new.
  Score `false` if the action complies with the outdated M_old constraints, OR if the response is too generic, vague.

Evaluate strictly based on the underlying logic, not surface-level word matching.

### Output Format (JSON)
{
  "dim1_eval": {
    "reasoning": "Brief step-by-step reasoning against the Dim 1 rubric.",
    "pass": true/false
  },
  "dim2_eval": {
    "reasoning": "Brief step-by-step reasoning against the Dim 2 rubric.",
    "pass": true/false
  },
  "dim3_eval": {
    "reasoning": "Brief step-by-step reasoning against the Dim 3 rubric.",
    "pass": true/false
  }
}"""


def build_user_prompt(info: Dict, responses: Dict) -> str:
    pq = info.get("probing_queries", {})
    return (
        f'[Ground Truth Context]\n'
        f'- M_old: "{info["M_old"]}"\n'
        f'- M_new: "{info["M_new"]}"\n'
        f'- Hidden Logic: {info.get("explanation", "(not provided)")}\n\n'
        f'--------------------------------------------------\n'
        f'[Dimension 1: Explicit Probing]\n'
        f'Question 1: {pq.get("dim1_query", "")}\n'
        f'Target Model Response 1: {responses.get("dim1_response", "")}\n\n'
        f'--------------------------------------------------\n'
        f'[Dimension 2: Adversarial Robustness]\n'
        f'Question 2: {pq.get("dim2_query", "")}\n'
        f'Target Model Response 2: {responses.get("dim2_response", "")}\n\n'
        f'--------------------------------------------------\n'
        f'[Dimension 3: Implicit Task]\n'
        f'Question 3: {pq.get("dim3_query", "")}\n'
        f'Target Model Response 3: {responses.get("dim3_response", "")}'
    )


def cohen_kappa(a: List[bool], b: List[bool]) -> float:
    n = len(a)
    if n == 0:
        return 0.0
    agree = sum(1 for x, y in zip(a, b) if x == y) / n
    pa_t = sum(a) / n
    pb_t = sum(b) / n
    pe = pa_t * pb_t + (1 - pa_t) * (1 - pb_t)
    return (agree - pe) / (1 - pe) if (1 - pe) > 0 else 1.0


def load_cache_gpt(uid: str) -> Optional[Dict]:
    path = CACHE_DIR / f"{uid}.json"
    return json.loads(path.read_text()) if path.exists() else None


def save_cache_gpt(uid: str, result: Dict) -> None:
    (CACHE_DIR / f"{uid}.json").write_text(json.dumps(result))


async def score_with_gpt5mini(
    sem: asyncio.Semaphore,
    client: Any,
    uid: str,
    user_prompt: str,
) -> Dict:
    cached = load_cache_gpt(uid)
    if cached is not None:
        return cached
    async with sem:
        try:
            resp = await client.chat.completions.create(
                model=SECOND_JUDGE_MODEL,
                messages=[
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {"role": "user",   "content": user_prompt},
                ],
                temperature=0,
                response_format={"type": "json_object"},
            )
            result = json.loads(resp.choices[0].message.content)
            save_cache_gpt(uid, result)
            return result
        except Exception as exc:
            return {"_error": str(exc)}


async def run_gpt5mini_all(tasks: List[Tuple[str, str]]) -> List[Dict]:
    from openai import AsyncOpenAI
    client = AsyncOpenAI(api_key=SECOND_JUDGE_KEY, base_url=SECOND_JUDGE_URL)
    sem = asyncio.Semaphore(CONCURRENCY)
    coros = [score_with_gpt5mini(sem, client, uid, prompt) for uid, prompt in tasks]
    results: List[Dict] = []
    for i, coro in enumerate(asyncio.as_completed(coros)):
        r = await coro
        results.append(r)
        if (i + 1) % 10 == 0:
            print(f"  [{i+1}/{len(tasks)}] GPT-5mini calls done", flush=True)
    return results


def get_qwen_scores(detail: Dict) -> Dict[str, bool]:
    ev = detail.get("evaluation", {})
    return {
        "dim1": bool(ev.get("dim1_eval", {}).get("pass")),
        "dim2": bool(ev.get("dim2_eval", {}).get("pass")),
        "dim3": bool(ev.get("dim3_eval", {}).get("pass")),
    }


def load_samples() -> Tuple[List[Dict], List[Dict], Dict, Dict]:
    """Load sampled details, info_map, and uid→sample_index map."""
    with open(DATA_PATH) as f:
        data = json.load(f)
    info_map = {s["uid"]: s for s in data}

    with open(SCORES_T1) as f:
        s_t1 = json.load(f)
    with open(SCORES_T2) as f:
        s_t2 = json.load(f)

    random.seed(42)
    t1_details = random.sample(s_t1["details"], N_SAMPLE_EACH)
    t2_details = random.sample(s_t2["details"], N_SAMPLE_EACH)

    # Build uid→answer_path index upfront (avoid O(n*m) glob)
    uid_to_ans: Dict[str, Path] = {}
    for d in sorted(ANSWERS_DIR.iterdir()):
        p = d / "answer.json"
        if p.exists():
            try:
                raw = json.loads(p.read_text())
                uid_to_ans[raw.get("uid", "")] = p
            except Exception:
                pass

    return t1_details + t2_details, info_map, uid_to_ans


def export_for_annotation(sampled: List[Dict], info_map: Dict, uid_to_ans: Dict) -> None:
    """Export human-readable annotation file + blank template."""
    readable = []
    template = []
    skipped = 0

    for detail in sampled:
        uid = detail["uid"]
        ans_path = uid_to_ans.get(uid)
        if ans_path is None:
            print(f"  WARNING: answer not found for uid={uid}, skipping", flush=True)
            skipped += 1
            continue
        raw = json.loads(ans_path.read_text())
        try:
            responses = ast.literal_eval(raw["target_model_responses"])
        except Exception:
            responses = raw.get("target_model_responses", {})
            if isinstance(responses, str):
                responses = {}

        info = info_map.get(uid, {})
        pq   = info.get("probing_queries", {})
        qwen = get_qwen_scores(detail)

        readable.append({
            "uid": uid,
            "type": detail.get("task_type", raw.get("type", "?")),
            "M_old": info.get("M_old", ""),
            "M_new": info.get("M_new", ""),
            "explanation": info.get("explanation", ""),
            "dim1_query":    pq.get("dim1_query", ""),
            "dim1_response": responses.get("dim1_response", ""),
            "dim2_query":    pq.get("dim2_query", ""),
            "dim2_response": responses.get("dim2_response", ""),
            "dim3_query":    pq.get("dim3_query", ""),
            "dim3_response": responses.get("dim3_response", ""),
            "qwen_dim1_pass": qwen["dim1"],
            "qwen_dim2_pass": qwen["dim2"],
            "qwen_dim3_pass": qwen["dim3"],
            "qwen_dim1_reasoning": detail.get("evaluation", {}).get("dim1_eval", {}).get("reasoning", ""),
            "qwen_dim2_reasoning": detail.get("evaluation", {}).get("dim2_eval", {}).get("reasoning", ""),
            "qwen_dim3_reasoning": detail.get("evaluation", {}).get("dim3_eval", {}).get("reasoning", ""),
        })
        # Blank annotation template — human fills in the pass fields
        template.append({
            "uid": uid,
            "type": detail.get("task_type", raw.get("type", "?")),
            # Human: set to true/false after reviewing
            "human_dim1_pass": None,
            "human_dim2_pass": None,
            "human_dim3_pass": None,
            "human_notes": "",
        })

    with open(EXPORT_READABLE, "w") as f:
        json.dump(readable, f, indent=2, ensure_ascii=False)
    with open(ANNOTATION_TMPL, "w") as f:
        json.dump(template, f, indent=2, ensure_ascii=False)

    print(f"\n导出完成: {len(readable)} 条 (跳过 {skipped} 条 answer 不存在)", flush=True)
    print(f"  可读版: {EXPORT_READABLE}", flush=True)
    print(f"  标注模板: {ANNOTATION_TMPL}", flush=True)
    print("\n请填写 annotation_template.json 里每条的 human_dim1_pass / dim2 / dim3 字段 (true/false)，", flush=True)
    print("填完后运行: python scripts/validate_judge_real.py --human-annotations runs/judge_validation_real/annotation_template.json", flush=True)


def compute_and_report(
    sampled: List[Dict],
    info_map: Dict,
    uid_to_ans: Dict,
    human_annots: Optional[Dict[str, Dict]],
    export_only: bool,
) -> None:

    if export_only:
        export_for_annotation(sampled, info_map, uid_to_ans)
        return

    # ── Build tasks for GPT-5 mini ────────────────────────────────────────────
    tasks: List[Tuple[str, str]] = []
    uid_to_detail: Dict[str, Dict] = {d["uid"]: d for d in sampled}

    for detail in sampled:
        uid = detail["uid"]
        ans_path = uid_to_ans.get(uid)
        if ans_path is None:
            continue
        raw = json.loads(ans_path.read_text())
        try:
            responses = ast.literal_eval(raw["target_model_responses"])
        except Exception:
            responses = raw.get("target_model_responses", {})
            if isinstance(responses, str):
                responses = {}
        info = info_map.get(uid, {})
        if not info:
            continue
        user_prompt = build_user_prompt(info, responses)
        tasks.append((uid, user_prompt))

    print(f"共 {len(tasks)} 条发给 GPT-5 mini 评分...", flush=True)
    gpt_results_raw = asyncio.run(run_gpt5mini_all(tasks))
    uid_to_gpt: Dict[str, Dict] = {uid: r for (uid, _), r in zip(tasks, gpt_results_raw)}

    # ── Build records ─────────────────────────────────────────────────────────
    records = []
    for detail in sampled:
        uid = detail["uid"]
        if uid not in uid_to_gpt:
            continue
        qwen    = get_qwen_scores(detail)
        gpt_raw = uid_to_gpt[uid]
        if "_error" in gpt_raw:
            print(f"  GPT error uid={uid}: {gpt_raw['_error']}", flush=True)
            continue
        gpt = {
            "dim1": bool(gpt_raw.get("dim1_eval", {}).get("pass")),
            "dim2": bool(gpt_raw.get("dim2_eval", {}).get("pass")),
            "dim3": bool(gpt_raw.get("dim3_eval", {}).get("pass")),
        }
        rec = {
            "uid": uid,
            "type": detail.get("task_type", "?"),
            "qwen_scores": qwen,
            "gpt5mini_scores": gpt,
            "agree_qwen_gpt_dim1": qwen["dim1"] == gpt["dim1"],
            "agree_qwen_gpt_dim2": qwen["dim2"] == gpt["dim2"],
            "agree_qwen_gpt_dim3": qwen["dim3"] == gpt["dim3"],
        }
        if human_annots and uid in human_annots:
            ha = human_annots[uid]
            human = {
                "dim1": ha.get("human_dim1_pass"),
                "dim2": ha.get("human_dim2_pass"),
                "dim3": ha.get("human_dim3_pass"),
            }
            rec["human_scores"] = human
            rec["agree_qwen_human_dim1"] = (human["dim1"] == qwen["dim1"]) if human["dim1"] is not None else None
            rec["agree_qwen_human_dim2"] = (human["dim2"] == qwen["dim2"]) if human["dim2"] is not None else None
            rec["agree_qwen_human_dim3"] = (human["dim3"] == qwen["dim3"]) if human["dim3"] is not None else None
        records.append(rec)

    n = len(records)
    print(f"\n{n} 条有效比较记录", flush=True)
    print(f"第二 judge 模型: {SECOND_JUDGE_MODEL}", flush=True)

    # ── GPT-5mini vs qwen metrics ─────────────────────────────────────────────
    print("\n=== GPT-5 mini vs qwen3.6-plus (跨家族模型一致率) ===")
    gpt_qw_all, qw_all_flat = [], []
    for dim in ["dim1", "dim2", "dim3"]:
        qw  = [r["qwen_scores"][dim]     for r in records]
        gpt = [r["gpt5mini_scores"][dim] for r in records]
        agree = sum(1 for a, b in zip(qw, gpt) if a == b) / n
        kappa = cohen_kappa(qw, gpt)
        print(f"  {dim}: agree={agree:.1%}  κ={kappa:.3f}")
        qw_all_flat += qw
        gpt_qw_all  += gpt

    overall_agree_gpt = sum(1 for a, b in zip(qw_all_flat, gpt_qw_all) if a == b) / len(qw_all_flat)
    overall_kappa_gpt = cohen_kappa(qw_all_flat, gpt_qw_all)
    print(f"  OVERALL: agree={overall_agree_gpt:.1%}  κ={overall_kappa_gpt:.3f}")

    # ── Human vs qwen metrics (if provided) ──────────────────────────────────
    human_summary = {}
    if human_annots:
        recs_with_human = [r for r in records if "human_scores" in r and
                           all(v is not None for v in r["human_scores"].values())]
        nh = len(recs_with_human)
        if nh > 0:
            print(f"\n=== Human annotation vs qwen3.6-plus (主证据, n={nh}) ===")
            hw_all, qw_h_all = [], []
            for dim in ["dim1", "dim2", "dim3"]:
                hu = [r["human_scores"][dim]  for r in recs_with_human]
                qw = [r["qwen_scores"][dim]   for r in recs_with_human]
                agree = sum(1 for a, b in zip(hu, qw) if a == b) / nh
                kappa = cohen_kappa(hu, qw)
                print(f"  {dim}: agree={agree:.1%}  κ={kappa:.3f}")
                hw_all += hu
                qw_h_all += qw
            overall_agree_human = sum(1 for a, b in zip(hw_all, qw_h_all) if a == b) / len(hw_all)
            overall_kappa_human = cohen_kappa(hw_all, qw_h_all)
            print(f"  OVERALL: agree={overall_agree_human:.1%}  κ={overall_kappa_human:.3f}")
            human_summary = {
                "n": nh,
                "overall_agreement": overall_agree_human,
                "overall_kappa": overall_kappa_human,
            }
        else:
            print("\nWARNING: 人工标注文件存在但无有效记录（请确认 human_dim1_pass 等字段已填 true/false）")

    # ── 保存结果 ──────────────────────────────────────────────────────────────
    output = {
        "n_answers": n,
        "second_judge_model": SECOND_JUDGE_MODEL,
        "primary_judge_model": "qwen3.6-plus",
        "cross_model_gpt5mini_vs_qwen": {
            "overall_agreement": overall_agree_gpt,
            "overall_kappa": overall_kappa_gpt,
            "per_dim": {
                dim: {
                    "agreement": sum(1 for r in records if r[f"agree_qwen_gpt_{dim}"]) / n,
                    "kappa": cohen_kappa(
                        [r["qwen_scores"][dim]     for r in records],
                        [r["gpt5mini_scores"][dim] for r in records],
                    ),
                }
                for dim in ["dim1", "dim2", "dim3"]
            },
        },
        "human_vs_qwen": human_summary,
        "records": records,
    }
    with open(OUT_PATH, "w") as f:
        json.dump(output, f, indent=2, ensure_ascii=False)
    print(f"\n结果保存到: {OUT_PATH}", flush=True)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--export-only", action="store_true",
                        help="只导出人工标注模板，不运行 GPT-5 mini")
    parser.add_argument("--human-annotations", type=str, default=None,
                        help="已填写的标注模板路径 (annotation_template.json)")
    args = parser.parse_args()

    sampled, info_map, uid_to_ans = load_samples()

    human_annots: Optional[Dict[str, Dict]] = None
    if args.human_annotations:
        with open(args.human_annotations) as f:
            raw_annots = json.load(f)
        human_annots = {a["uid"]: a for a in raw_annots}
        print(f"加载人工标注: {len(human_annots)} 条", flush=True)

    if args.export_only:
        export_for_annotation(sampled, info_map, uid_to_ans)
    else:
        compute_and_report(sampled, info_map, uid_to_ans, human_annots, export_only=False)


if __name__ == "__main__":
    main()
